Update meteor install and add nginx and pow

diff --git a/meteor-and-node/install b/meteor-and-node/install
--- a/meteor-and-node/install
+++ b/meteor-and-node/install
@@ -1,14 +1,62 @@
 #!/usr/bin/env bash
+cd "$(dirname "${BASH_SOURCE}")"
+WD=`pwd`
+
+echo 'Installing nginx, pow, npm, coffee-script, coffeelint, meteor...'
+
+# Ask for the administrator password upfront
+sudo -v
+
+# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
+while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
 # Install Node.js
-brew doctor
-brew install node
+# brew doctor
+# brew install node
+
+# Install nginx
+# brew install nginx
+NGINX='/usr/local/etc/nginx'
+CERT='/tmp/cert'
+mkdir -p ${NGINX}/sites-enabled
+mkdir -p ${NGINX}/ssl
+mkdir -p ${CERT}
+cd ${CERT}
+openssl genrsa -out dev.key 1024
+openssl req -new -key dev.key -out dev.csr -subj '/C=US/ST=CA/L=Name/O=Organization/OU=Unit/CN=*.dev'
+rm dev.key.bak
+cp dev.key dev.key.bak
+openssl rsa -in dev.key.bak -out dev.key
+openssl x509 -req -days 365 -in dev.csr -signkey dev.key -out dev.crt
+mv dev.* ${NGINX}/ssl
+rm -f ${NGINX}/nginx.conf
+cd $WD
+ln -s nginx.conf ${NGINX}/nginx.conf
+
+# Install pow
+# brew install pow
+mkdir -p ~/Library/Application\ Support/Pow/Hosts
+rm -f ~/.pow
+ln -s ~/Library/Application\ Support/Pow/Hosts ~/.pow
+sudo pow --install-system
+pow --install-local
+sudo launchctl load -w /Library/LaunchDaemons/cx.pow.firewall.plist
+launchctl load -w ~/Library/LaunchAgents/cx.pow.powd.plist
 
 # Node.js packages
-npm install -g coffee-script coffeelint
+# npm install -g coffee-script coffeelint
 
 # Install Meteor
-curl https://install.meteor.com/ | sh
+# curl https://install.meteor.com/ | sh
 
 # Cleanup
-brew cleanup
+# brew cleanup
+
+IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`
+
+echo
+echo 'To open your app locally:'
+echo 'open https://APP.dev/'
+echo
+echo 'From another computer in your network:'
+echo "open https://APP.${IP}.xip.io/"
